# Generated by Django 2.2.5 on 2020-05-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='quests',
            new_name='guests',
        ),
    ]
